### ISSUE TITLE
Add the install steps to the main README.md

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [vmware-tanzu/octant-plugin-for-knative#188]
Hi,
I only just learnt that I can install the plugin by simply downloading the js file on the release page to the correct folder.
Previously, I had quickly glanced at the README.md and incorrectly assumed that I needed to setup npm locally to get the plugin going.

In case its not only me who has run into this, it would be useful to have the instructions that are listed [v0.3.0 release](https://github.com/vmware-tanzu/octant-plugin-for-knative/releases/tag/v0.3.0) shown more prominently in the [README](https://github.com/vmware-tanzu/octant-plugin-for-knative/blob/main/README.md)

**Comment by rguske** [comment]
+1 on this one.
