### ISSUE TITLE
Create a new service in modal

### ISSUE THREAD

**Issue by amakhija** [vmware-tanzu/octant-plugin-for-knative#45]
Currently, the plugin redirects you to a new page to create a service where the form for a new service appears when you click "Configure". Instead, when selecting "Create Service", the plugin should open a new modal to create a service using an image.

Design:
![image](https://user-images.githubusercontent.com/20206612/96007753-0ca52000-0dfc-11eb-9f7f-debda378ac48.png)

**Comment by scothis** [comment]
We're currently blocked as forms in modals are broken in Octant

**Comment by scothis** [comment]
#53 disables the 'New Service' and 'Configure' forms by default. We can continue to iterate on them while Octant's form support improves without giving users a broken experiance.
